# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Vagrant box
  #config.vm.box = "ubuntu/trusty64"
  config.vm.box = "roboxes/alpine38"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  #config.vm.network "private_network", ip: "192.168.33.10"

  # Configure VM provider options
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = "4"
    #vb.customize ["modifyvm", :id, "--cpu-profile", "Intel Core i7-6700K"]
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end

  config.vm.provision "shell", path: "../scripts/install.sh"
end
